### ISSUE TITLE
Help with installation first steps

### ISSUE THREAD

**Issue by DerDominik** [jzyrobert/openeats-docker#1]
I installed, configured (as far as I think) and started the docker.
It seems that it connects to my mariadb-docker, as there are some tables and data inserted.

I start the webinterface of OpenEats, but I can't login with the standard user/password "openeats".

Maybe you can help me?

I changed only following configuration:
Network mode -> Bridge with portmapping port 80 -> 8300 (I can reach openeats with port 8300)
MYSQL_PORT -> 3307 (MariaDB is working parallel to another SQL Server)
NODE_LOCALE -> de

In the log are also no erros.

Do you've an idea?

**Comment by jzyrobert** [comment]
You might have to set SUPERUSER_NAME and SUPERUSER_PASSWORD

Can you share a screenshot of your container settings (with passwords and stuff blacked out)

**Comment by DerDominik** [comment]
They are almost all on default values, also SUPERUSER_NAME and SUPERUSER_PASSWORD
Attached is a screenshot
![openeats](https://user-images.githubusercontent.com/16927324/84567087-9ec9e880-ad76-11ea-95a8-a2198a0669d5.jpg)

**Comment by jzyrobert** [comment]
Hmm, what if you open the dev console (F12) in the browser when you try to login, is there an error?

**Comment by DerDominik** [comment]
I'm getting a javascript error on every browser, I've tested
![openeats](https://user-images.githubusercontent.com/16927324/84567945-79d87400-ad7c-11ea-9b91-7d193d609d1d.jpg)

**Comment by jzyrobert** [comment]
Ah, that isn't the console. You see the tab right of "Elements" which says "Console", check that one.

**Comment by DerDominik** [comment]
Ah ok, sorry
Here are some more messages, which maybe help
![1](https://user-images.githubusercontent.com/16927324/84568438-cbcec900-ad7f-11ea-9214-39650b2ff12e.jpg)

The upper part is before login
And the bottom part is after login

**Comment by jzyrobert** [comment]
Hmm, it looks like API requests are being denied.

Have you added ALLOWED_HOST : * to the container?

**Comment by DerDominik** [comment]
That was the missing option
Now it's working :-)
Many thanks for your help

**Comment by jzyrobert** [comment]
Np
